server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Market
    username: postgres
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: clientes
        show-sql: true

